name: Build V8  

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: ['10.6.194.17']
        platform: ['x64']
        lib: ['shared'] #, 'monolith']
    steps:
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        toolset: '14.34.31933'
