name: Build V8  

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: ['10.6.194.17']
        platform: ['x64']
        lib: ['shared'] #, 'monolith']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python2
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        toolset: '14.2'
    - name: Build
      run: python build.py --version=${{ matrix.version }} --platform=${{ matrix.platform }} --libs=${{ matrix.lib }}
